CREATE TABLE IF NOT EXISTS countries_flags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    iso2 CHAR(2),
    calling_code VARCHAR(20),
    flag VARCHAR(10)
);

INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Aruba', 'AW', '+297', '🇦🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Afghanistan', 'AF', '+93', '🇦🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Angola', 'AO', '+244', '🇦🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Anguilla', 'AI', '+1264', '🇦🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Åland Islands', 'AX', '+35818', '🇦🇽');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Albania', 'AL', '+355', '🇦🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Andorra', 'AD', '+376', '🇦🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('United Arab Emirates', 'AE', '+971', '🇦🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Argentina', 'AR', '+54', '🇦🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Armenia', 'AM', '+374', '🇦🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('American Samoa', 'AS', '+1684', '🇦🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Antarctica', 'AQ', '', '🇦🇶');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('French Southern and Antarctic Lands', 'TF', '+262', '🇹🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Antigua and Barbuda', 'AG', '+1268', '🇦🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Australia', 'AU', '+61', '🇦🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Austria', 'AT', '+43', '🇦🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Azerbaijan', 'AZ', '+994', '🇦🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Burundi', 'BI', '+257', '🇧🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Belgium', 'BE', '+32', '🇧🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Benin', 'BJ', '+229', '🇧🇯');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Burkina Faso', 'BF', '+226', '🇧🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bangladesh', 'BD', '+880', '🇧🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bulgaria', 'BG', '+359', '🇧🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bahrain', 'BH', '+973', '🇧🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bahamas', 'BS', '+1242', '🇧🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bosnia and Herzegovina', 'BA', '+387', '🇧🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Barthélemy', 'BL', '+590', '🇧🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', '+290', '🇸🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Belarus', 'BY', '+375', '🇧🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Belize', 'BZ', '+501', '🇧🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bermuda', 'BM', '+1441', '🇧🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bolivia', 'BO', '+591', '🇧🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Caribbean Netherlands', 'BQ', '+599', '');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Brazil', 'BR', '+55', '🇧🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Barbados', 'BB', '+1246', '🇧🇧');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Brunei', 'BN', '+673', '🇧🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bhutan', 'BT', '+975', '🇧🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Bouvet Island', 'BV', '+47', '🇧🇻');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Botswana', 'BW', '+267', '🇧🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Central African Republic', 'CF', '+236', '🇨🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Canada', 'CA', '+1204', '🇨🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cocos (Keeling) Islands', 'CC', '+61', '🇨🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Switzerland', 'CH', '+41', '🇨🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Chile', 'CL', '+56', '🇨🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('China', 'CN', '+86', '🇨🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Ivory Coast', 'CI', '+225', '🇨🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cameroon', 'CM', '+237', '🇨🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('DR Congo', 'CD', '+243', '🇨🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Congo', 'CG', '+242', '🇨🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cook Islands', 'CK', '+682', '🇨🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Colombia', 'CO', '+57', '🇨🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Comoros', 'KM', '+269', '🇰🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cape Verde', 'CV', '+238', '🇨🇻');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Costa Rica', 'CR', '+506', '🇨🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cuba', 'CU', '+53', '🇨🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Curaçao', 'CW', '+599', '🇨🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Christmas Island', 'CX', '+61', '🇨🇽');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cayman Islands', 'KY', '+1345', '🇰🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cyprus', 'CY', '+357', '🇨🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Czechia', 'CZ', '+420', '🇨🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Germany', 'DE', '+49', '🇩🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Djibouti', 'DJ', '+253', '🇩🇯');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Dominica', 'DM', '+1767', '🇩🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Denmark', 'DK', '+45', '🇩🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Dominican Republic', 'DO', '+1809', '🇩🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Algeria', 'DZ', '+213', '🇩🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Ecuador', 'EC', '+593', '🇪🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Egypt', 'EG', '+20', '🇪🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Eritrea', 'ER', '+291', '🇪🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Western Sahara', 'EH', '+2125288', '🇪🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Spain', 'ES', '+34', '🇪🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Estonia', 'EE', '+372', '🇪🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Ethiopia', 'ET', '+251', '🇪🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Finland', 'FI', '+358', '🇫🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Fiji', 'FJ', '+679', '🇫🇯');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Falkland Islands', 'FK', '+500', '🇫🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('France', 'FR', '+33', '🇫🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Faroe Islands', 'FO', '+298', '🇫🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Micronesia', 'FM', '+691', '🇫🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Gabon', 'GA', '+241', '🇬🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('United Kingdom', 'GB', '+44', '🇬🇧');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Georgia', 'GE', '+995', '🇬🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guernsey', 'GG', '+44', '🇬🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Ghana', 'GH', '+233', '🇬🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Gibraltar', 'GI', '+350', '🇬🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guinea', 'GN', '+224', '🇬🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guadeloupe', 'GP', '+590', '🇬🇵');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Gambia', 'GM', '+220', '🇬🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guinea-Bissau', 'GW', '+245', '🇬🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Equatorial Guinea', 'GQ', '+240', '🇬🇶');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Greece', 'GR', '+30', '🇬🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Grenada', 'GD', '+1473', '🇬🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Greenland', 'GL', '+299', '🇬🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guatemala', 'GT', '+502', '🇬🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('French Guiana', 'GF', '+594', '🇬🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guam', 'GU', '+1671', '🇬🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Guyana', 'GY', '+592', '🇬🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Hong Kong', 'HK', '+852', '🇭🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Heard Island and McDonald Islands', 'HM', '', '🇭🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Honduras', 'HN', '+504', '🇭🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Croatia', 'HR', '+385', '🇭🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Haiti', 'HT', '+509', '🇭🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Hungary', 'HU', '+36', '🇭🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Indonesia', 'ID', '+62', '🇮🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Isle of Man', 'IM', '+44', '🇮🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('India', 'IN', '+91', '🇮🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('British Indian Ocean Territory', 'IO', '+246', '🇮🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Ireland', 'IE', '+353', '🇮🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Iran', 'IR', '+98', '🇮🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Iraq', 'IQ', '+964', '🇮🇶');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Iceland', 'IS', '+354', '🇮🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Israel', 'IL', '+972', '🇮🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Italy', 'IT', '+39', '🇮🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Jamaica', 'JM', '+1876', '🇯🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Jersey', 'JE', '+44', '🇯🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Jordan', 'JO', '+962', '🇯🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Japan', 'JP', '+81', '🇯🇵');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Kazakhstan', 'KZ', '+76', '🇰🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Kenya', 'KE', '+254', '🇰🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Kyrgyzstan', 'KG', '+996', '🇰🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Cambodia', 'KH', '+855', '🇰🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Kiribati', 'KI', '+686', '🇰🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Kitts and Nevis', 'KN', '+1869', '🇰🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('South Korea', 'KR', '+82', '🇰🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Kosovo', 'XK', '+383', '🇽🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Kuwait', 'KW', '+965', '🇰🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Laos', 'LA', '+856', '🇱🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Lebanon', 'LB', '+961', '🇱🇧');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Liberia', 'LR', '+231', '🇱🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Libya', 'LY', '+218', '🇱🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Lucia', 'LC', '+1758', '🇱🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Liechtenstein', 'LI', '+423', '🇱🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Sri Lanka', 'LK', '+94', '🇱🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Lesotho', 'LS', '+266', '🇱🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Lithuania', 'LT', '+370', '🇱🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Luxembourg', 'LU', '+352', '🇱🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Latvia', 'LV', '+371', '🇱🇻');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Macau', 'MO', '+853', '🇲🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Martin', 'MF', '+590', '🇲🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Morocco', 'MA', '+212', '🇲🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Monaco', 'MC', '+377', '🇲🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Moldova', 'MD', '+373', '🇲🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Madagascar', 'MG', '+261', '🇲🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Maldives', 'MV', '+960', '🇲🇻');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mexico', 'MX', '+52', '🇲🇽');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Marshall Islands', 'MH', '+692', '🇲🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('North Macedonia', 'MK', '+389', '🇲🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mali', 'ML', '+223', '🇲🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Malta', 'MT', '+356', '🇲🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Myanmar', 'MM', '+95', '🇲🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Montenegro', 'ME', '+382', '🇲🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mongolia', 'MN', '+976', '🇲🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Northern Mariana Islands', 'MP', '+1670', '🇲🇵');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mozambique', 'MZ', '+258', '🇲🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mauritania', 'MR', '+222', '🇲🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Montserrat', 'MS', '+1664', '🇲🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Martinique', 'MQ', '+596', '🇲🇶');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mauritius', 'MU', '+230', '🇲🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Malawi', 'MW', '+265', '🇲🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Malaysia', 'MY', '+60', '🇲🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Mayotte', 'YT', '+262', '🇾🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Namibia', 'NA', '+264', '🇳🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('New Caledonia', 'NC', '+687', '🇳🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Niger', 'NE', '+227', '🇳🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Norfolk Island', 'NF', '+672', '🇳🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Nigeria', 'NG', '+234', '🇳🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Nicaragua', 'NI', '+505', '🇳🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Niue', 'NU', '+683', '🇳🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Netherlands', 'NL', '+31', '🇳🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Norway', 'NO', '+47', '🇳🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Nepal', 'NP', '+977', '🇳🇵');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Nauru', 'NR', '+674', '🇳🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('New Zealand', 'NZ', '+64', '🇳🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Oman', 'OM', '+968', '🇴🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Pakistan', 'PK', '+92', '🇵🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Panama', 'PA', '+507', '🇵🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Pitcairn Islands', 'PN', '+64', '🇵🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Peru', 'PE', '+51', '🇵🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Philippines', 'PH', '+63', '🇵🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Palau', 'PW', '+680', '🇵🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Papua New Guinea', 'PG', '+675', '🇵🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Poland', 'PL', '+48', '🇵🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Puerto Rico', 'PR', '+1787', '🇵🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('North Korea', 'KP', '+850', '🇰🇵');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Portugal', 'PT', '+351', '🇵🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Paraguay', 'PY', '+595', '🇵🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Palestine', 'PS', '+970', '🇵🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('French Polynesia', 'PF', '+689', '🇵🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Qatar', 'QA', '+974', '🇶🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Réunion', 'RE', '+262', '🇷🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Romania', 'RO', '+40', '🇷🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Russia', 'RU', '+73', '🇷🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Rwanda', 'RW', '+250', '🇷🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saudi Arabia', 'SA', '+966', '🇸🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Sudan', 'SD', '+249', '🇸🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Senegal', 'SN', '+221', '🇸🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Singapore', 'SG', '+65', '🇸🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('South Georgia', 'GS', '+500', '🇬🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Svalbard and Jan Mayen', 'SJ', '+4779', '🇸🇯');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Solomon Islands', 'SB', '+677', '🇸🇧');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Sierra Leone', 'SL', '+232', '🇸🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('El Salvador', 'SV', '+503', '🇸🇻');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('San Marino', 'SM', '+378', '🇸🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Somalia', 'SO', '+252', '🇸🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Pierre and Miquelon', 'PM', '+508', '🇵🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Serbia', 'RS', '+381', '🇷🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('South Sudan', 'SS', '+211', '🇸🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('São Tomé and Príncipe', 'ST', '+239', '🇸🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Suriname', 'SR', '+597', '🇸🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Slovakia', 'SK', '+421', '🇸🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Slovenia', 'SI', '+386', '🇸🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Sweden', 'SE', '+46', '🇸🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Eswatini', 'SZ', '+268', '🇸🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Sint Maarten', 'SX', '+1721', '🇸🇽');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Seychelles', 'SC', '+248', '🇸🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Syria', 'SY', '+963', '🇸🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Turks and Caicos Islands', 'TC', '+1649', '🇹🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Chad', 'TD', '+235', '🇹🇩');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Togo', 'TG', '+228', '🇹🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Thailand', 'TH', '+66', '🇹🇭');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Tajikistan', 'TJ', '+992', '🇹🇯');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Tokelau', 'TK', '+690', '🇹🇰');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Turkmenistan', 'TM', '+993', '🇹🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Timor-Leste', 'TL', '+670', '🇹🇱');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Tonga', 'TO', '+676', '🇹🇴');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Trinidad and Tobago', 'TT', '+1868', '🇹🇹');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Tunisia', 'TN', '+216', '🇹🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Türkiye', 'TR', '+90', '🇹🇷');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Tuvalu', 'TV', '+688', '🇹🇻');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Taiwan', 'TW', '+886', '🇹🇼');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Tanzania', 'TZ', '+255', '🇹🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Uganda', 'UG', '+256', '🇺🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Ukraine', 'UA', '+380', '🇺🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('United States Minor Outlying Islands', 'UM', '+268', '🇺🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Uruguay', 'UY', '+598', '🇺🇾');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('United States', 'US', '+1201', '🇺🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Uzbekistan', 'UZ', '+998', '🇺🇿');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Vatican City', 'VA', '+3906698', '🇻🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Saint Vincent and the Grenadines', 'VC', '+1784', '🇻🇨');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Venezuela', 'VE', '+58', '🇻🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('British Virgin Islands', 'VG', '+1284', '🇻🇬');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('United States Virgin Islands', 'VI', '+1340', '🇻🇮');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Vietnam', 'VN', '+84', '🇻🇳');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Vanuatu', 'VU', '+678', '🇻🇺');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Wallis and Futuna', 'WF', '+681', '🇼🇫');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Samoa', 'WS', '+685', '🇼🇸');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Yemen', 'YE', '+967', '🇾🇪');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('South Africa', 'ZA', '+27', '🇿🇦');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Zambia', 'ZM', '+260', '🇿🇲');
INSERT INTO countries_flags (name, iso2, calling_code, flag) VALUES ('Zimbabwe', 'ZW', '+263', '🇿🇼');
