CREATE TABLE IF NOT EXISTS countries_basic (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    iso2 CHAR(2),
    iso3 CHAR(3),
    calling_code VARCHAR(20)
);

INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Aruba', 'AW', 'ABW', '+297');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Afghanistan', 'AF', 'AFG', '+93');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Angola', 'AO', 'AGO', '+244');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Anguilla', 'AI', 'AIA', '+1264');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Åland Islands', 'AX', 'ALA', '+35818');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Albania', 'AL', 'ALB', '+355');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Andorra', 'AD', 'AND', '+376');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('United Arab Emirates', 'AE', 'ARE', '+971');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Argentina', 'AR', 'ARG', '+54');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Armenia', 'AM', 'ARM', '+374');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('American Samoa', 'AS', 'ASM', '+1684');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Antarctica', 'AQ', 'ATA', '');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('French Southern and Antarctic Lands', 'TF', 'ATF', '+262');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Antigua and Barbuda', 'AG', 'ATG', '+1268');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Australia', 'AU', 'AUS', '+61');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Austria', 'AT', 'AUT', '+43');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Azerbaijan', 'AZ', 'AZE', '+994');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Burundi', 'BI', 'BDI', '+257');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Belgium', 'BE', 'BEL', '+32');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Benin', 'BJ', 'BEN', '+229');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Burkina Faso', 'BF', 'BFA', '+226');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bangladesh', 'BD', 'BGD', '+880');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bulgaria', 'BG', 'BGR', '+359');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bahrain', 'BH', 'BHR', '+973');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bahamas', 'BS', 'BHS', '+1242');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', '+387');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Barthélemy', 'BL', 'BLM', '+590');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '+290');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Belarus', 'BY', 'BLR', '+375');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Belize', 'BZ', 'BLZ', '+501');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bermuda', 'BM', 'BMU', '+1441');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bolivia', 'BO', 'BOL', '+591');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Caribbean Netherlands', 'BQ', 'BES', '+599');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Brazil', 'BR', 'BRA', '+55');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Barbados', 'BB', 'BRB', '+1246');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Brunei', 'BN', 'BRN', '+673');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bhutan', 'BT', 'BTN', '+975');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Bouvet Island', 'BV', 'BVT', '+47');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Botswana', 'BW', 'BWA', '+267');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Central African Republic', 'CF', 'CAF', '+236');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Canada', 'CA', 'CAN', '+1204');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cocos (Keeling) Islands', 'CC', 'CCK', '+61');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Switzerland', 'CH', 'CHE', '+41');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Chile', 'CL', 'CHL', '+56');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('China', 'CN', 'CHN', '+86');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Ivory Coast', 'CI', 'CIV', '+225');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cameroon', 'CM', 'CMR', '+237');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('DR Congo', 'CD', 'COD', '+243');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Congo', 'CG', 'COG', '+242');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cook Islands', 'CK', 'COK', '+682');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Colombia', 'CO', 'COL', '+57');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Comoros', 'KM', 'COM', '+269');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cape Verde', 'CV', 'CPV', '+238');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Costa Rica', 'CR', 'CRI', '+506');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cuba', 'CU', 'CUB', '+53');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Curaçao', 'CW', 'CUW', '+599');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Christmas Island', 'CX', 'CXR', '+61');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cayman Islands', 'KY', 'CYM', '+1345');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cyprus', 'CY', 'CYP', '+357');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Czechia', 'CZ', 'CZE', '+420');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Germany', 'DE', 'DEU', '+49');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Djibouti', 'DJ', 'DJI', '+253');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Dominica', 'DM', 'DMA', '+1767');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Denmark', 'DK', 'DNK', '+45');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Dominican Republic', 'DO', 'DOM', '+1809');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Algeria', 'DZ', 'DZA', '+213');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Ecuador', 'EC', 'ECU', '+593');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Egypt', 'EG', 'EGY', '+20');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Eritrea', 'ER', 'ERI', '+291');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Western Sahara', 'EH', 'ESH', '+2125288');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Spain', 'ES', 'ESP', '+34');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Estonia', 'EE', 'EST', '+372');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Ethiopia', 'ET', 'ETH', '+251');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Finland', 'FI', 'FIN', '+358');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Fiji', 'FJ', 'FJI', '+679');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Falkland Islands', 'FK', 'FLK', '+500');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('France', 'FR', 'FRA', '+33');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Faroe Islands', 'FO', 'FRO', '+298');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Micronesia', 'FM', 'FSM', '+691');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Gabon', 'GA', 'GAB', '+241');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('United Kingdom', 'GB', 'GBR', '+44');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Georgia', 'GE', 'GEO', '+995');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guernsey', 'GG', 'GGY', '+44');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Ghana', 'GH', 'GHA', '+233');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Gibraltar', 'GI', 'GIB', '+350');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guinea', 'GN', 'GIN', '+224');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guadeloupe', 'GP', 'GLP', '+590');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Gambia', 'GM', 'GMB', '+220');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guinea-Bissau', 'GW', 'GNB', '+245');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', '+240');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Greece', 'GR', 'GRC', '+30');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Grenada', 'GD', 'GRD', '+1473');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Greenland', 'GL', 'GRL', '+299');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guatemala', 'GT', 'GTM', '+502');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('French Guiana', 'GF', 'GUF', '+594');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guam', 'GU', 'GUM', '+1671');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Guyana', 'GY', 'GUY', '+592');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Hong Kong', 'HK', 'HKG', '+852');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Heard Island and McDonald Islands', 'HM', 'HMD', '');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Honduras', 'HN', 'HND', '+504');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Croatia', 'HR', 'HRV', '+385');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Haiti', 'HT', 'HTI', '+509');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Hungary', 'HU', 'HUN', '+36');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Indonesia', 'ID', 'IDN', '+62');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Isle of Man', 'IM', 'IMN', '+44');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('India', 'IN', 'IND', '+91');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('British Indian Ocean Territory', 'IO', 'IOT', '+246');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Ireland', 'IE', 'IRL', '+353');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Iran', 'IR', 'IRN', '+98');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Iraq', 'IQ', 'IRQ', '+964');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Iceland', 'IS', 'ISL', '+354');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Israel', 'IL', 'ISR', '+972');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Italy', 'IT', 'ITA', '+39');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Jamaica', 'JM', 'JAM', '+1876');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Jersey', 'JE', 'JEY', '+44');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Jordan', 'JO', 'JOR', '+962');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Japan', 'JP', 'JPN', '+81');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Kazakhstan', 'KZ', 'KAZ', '+76');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Kenya', 'KE', 'KEN', '+254');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Kyrgyzstan', 'KG', 'KGZ', '+996');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Cambodia', 'KH', 'KHM', '+855');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Kiribati', 'KI', 'KIR', '+686');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Kitts and Nevis', 'KN', 'KNA', '+1869');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('South Korea', 'KR', 'KOR', '+82');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Kosovo', 'XK', 'UNK', '+383');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Kuwait', 'KW', 'KWT', '+965');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Laos', 'LA', 'LAO', '+856');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Lebanon', 'LB', 'LBN', '+961');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Liberia', 'LR', 'LBR', '+231');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Libya', 'LY', 'LBY', '+218');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Lucia', 'LC', 'LCA', '+1758');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Liechtenstein', 'LI', 'LIE', '+423');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Sri Lanka', 'LK', 'LKA', '+94');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Lesotho', 'LS', 'LSO', '+266');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Lithuania', 'LT', 'LTU', '+370');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Luxembourg', 'LU', 'LUX', '+352');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Latvia', 'LV', 'LVA', '+371');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Macau', 'MO', 'MAC', '+853');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Martin', 'MF', 'MAF', '+590');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Morocco', 'MA', 'MAR', '+212');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Monaco', 'MC', 'MCO', '+377');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Moldova', 'MD', 'MDA', '+373');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Madagascar', 'MG', 'MDG', '+261');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Maldives', 'MV', 'MDV', '+960');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mexico', 'MX', 'MEX', '+52');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Marshall Islands', 'MH', 'MHL', '+692');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('North Macedonia', 'MK', 'MKD', '+389');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mali', 'ML', 'MLI', '+223');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Malta', 'MT', 'MLT', '+356');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Myanmar', 'MM', 'MMR', '+95');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Montenegro', 'ME', 'MNE', '+382');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mongolia', 'MN', 'MNG', '+976');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Northern Mariana Islands', 'MP', 'MNP', '+1670');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mozambique', 'MZ', 'MOZ', '+258');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mauritania', 'MR', 'MRT', '+222');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Montserrat', 'MS', 'MSR', '+1664');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Martinique', 'MQ', 'MTQ', '+596');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mauritius', 'MU', 'MUS', '+230');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Malawi', 'MW', 'MWI', '+265');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Malaysia', 'MY', 'MYS', '+60');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Mayotte', 'YT', 'MYT', '+262');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Namibia', 'NA', 'NAM', '+264');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('New Caledonia', 'NC', 'NCL', '+687');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Niger', 'NE', 'NER', '+227');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Norfolk Island', 'NF', 'NFK', '+672');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Nigeria', 'NG', 'NGA', '+234');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Nicaragua', 'NI', 'NIC', '+505');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Niue', 'NU', 'NIU', '+683');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Netherlands', 'NL', 'NLD', '+31');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Norway', 'NO', 'NOR', '+47');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Nepal', 'NP', 'NPL', '+977');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Nauru', 'NR', 'NRU', '+674');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('New Zealand', 'NZ', 'NZL', '+64');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Oman', 'OM', 'OMN', '+968');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Pakistan', 'PK', 'PAK', '+92');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Panama', 'PA', 'PAN', '+507');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Pitcairn Islands', 'PN', 'PCN', '+64');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Peru', 'PE', 'PER', '+51');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Philippines', 'PH', 'PHL', '+63');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Palau', 'PW', 'PLW', '+680');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Papua New Guinea', 'PG', 'PNG', '+675');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Poland', 'PL', 'POL', '+48');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Puerto Rico', 'PR', 'PRI', '+1787');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('North Korea', 'KP', 'PRK', '+850');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Portugal', 'PT', 'PRT', '+351');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Paraguay', 'PY', 'PRY', '+595');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Palestine', 'PS', 'PSE', '+970');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('French Polynesia', 'PF', 'PYF', '+689');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Qatar', 'QA', 'QAT', '+974');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Réunion', 'RE', 'REU', '+262');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Romania', 'RO', 'ROU', '+40');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Russia', 'RU', 'RUS', '+73');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Rwanda', 'RW', 'RWA', '+250');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saudi Arabia', 'SA', 'SAU', '+966');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Sudan', 'SD', 'SDN', '+249');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Senegal', 'SN', 'SEN', '+221');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Singapore', 'SG', 'SGP', '+65');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('South Georgia', 'GS', 'SGS', '+500');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Svalbard and Jan Mayen', 'SJ', 'SJM', '+4779');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Solomon Islands', 'SB', 'SLB', '+677');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Sierra Leone', 'SL', 'SLE', '+232');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('El Salvador', 'SV', 'SLV', '+503');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('San Marino', 'SM', 'SMR', '+378');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Somalia', 'SO', 'SOM', '+252');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Pierre and Miquelon', 'PM', 'SPM', '+508');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Serbia', 'RS', 'SRB', '+381');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('South Sudan', 'SS', 'SSD', '+211');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('São Tomé and Príncipe', 'ST', 'STP', '+239');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Suriname', 'SR', 'SUR', '+597');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Slovakia', 'SK', 'SVK', '+421');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Slovenia', 'SI', 'SVN', '+386');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Sweden', 'SE', 'SWE', '+46');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Eswatini', 'SZ', 'SWZ', '+268');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Sint Maarten', 'SX', 'SXM', '+1721');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Seychelles', 'SC', 'SYC', '+248');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Syria', 'SY', 'SYR', '+963');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Turks and Caicos Islands', 'TC', 'TCA', '+1649');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Chad', 'TD', 'TCD', '+235');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Togo', 'TG', 'TGO', '+228');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Thailand', 'TH', 'THA', '+66');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Tajikistan', 'TJ', 'TJK', '+992');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Tokelau', 'TK', 'TKL', '+690');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Turkmenistan', 'TM', 'TKM', '+993');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Timor-Leste', 'TL', 'TLS', '+670');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Tonga', 'TO', 'TON', '+676');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Trinidad and Tobago', 'TT', 'TTO', '+1868');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Tunisia', 'TN', 'TUN', '+216');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Türkiye', 'TR', 'TUR', '+90');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Tuvalu', 'TV', 'TUV', '+688');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Taiwan', 'TW', 'TWN', '+886');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Tanzania', 'TZ', 'TZA', '+255');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Uganda', 'UG', 'UGA', '+256');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Ukraine', 'UA', 'UKR', '+380');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI', '+268');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Uruguay', 'UY', 'URY', '+598');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('United States', 'US', 'USA', '+1201');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Uzbekistan', 'UZ', 'UZB', '+998');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Vatican City', 'VA', 'VAT', '+3906698');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VCT', '+1784');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Venezuela', 'VE', 'VEN', '+58');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('British Virgin Islands', 'VG', 'VGB', '+1284');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('United States Virgin Islands', 'VI', 'VIR', '+1340');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Vietnam', 'VN', 'VNM', '+84');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Vanuatu', 'VU', 'VUT', '+678');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Wallis and Futuna', 'WF', 'WLF', '+681');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Samoa', 'WS', 'WSM', '+685');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Yemen', 'YE', 'YEM', '+967');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('South Africa', 'ZA', 'ZAF', '+27');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Zambia', 'ZM', 'ZMB', '+260');
INSERT INTO countries_basic (name, iso2, iso3, calling_code) VALUES ('Zimbabwe', 'ZW', 'ZWE', '+263');
